from dataclasses import dataclass
from typing import List, Dict, Optional
from datetime import datetime
import uuid


@dataclass
class TextChunk:
    """A segment of extracted book content that has been cleaned and prepared for embedding generation."""

    id: str
    content: str
    source_url: str
    chunk_index: int
    created_at: datetime
    word_count: int
    char_count: int
    metadata: Dict[str, str]

    def __post_init__(self):
        """Validate the TextChunk after initialization."""
        if not self.content.strip():
            raise ValueError("Content cannot be empty")
        if len(self.content) < 10:
            raise ValueError("Content must be at least 10 characters")
        if len(self.content) > 5000:  # Reasonable upper limit
            raise ValueError("Content exceeds maximum length of 5000 characters")
        if not self.source_url:
            raise ValueError("Source URL cannot be empty")


@dataclass
class EmbeddingVector:
    """A high-dimensional numerical representation of text content generated by Cohere models."""

    id: str
    vector: List[float]
    text_chunk_id: str
    model_name: str
    created_at: datetime
    dimension: int

    def __post_init__(self):
        """Validate the EmbeddingVector after initialization."""
        if not self.vector:
            raise ValueError("Vector cannot be empty")
        if len(self.vector) != self.dimension:
            raise ValueError(f"Vector length ({len(self.vector)}) does not match expected dimension ({self.dimension})")
        if not self.text_chunk_id:
            raise ValueError("Text chunk ID cannot be empty")
        if not self.model_name:
            raise ValueError("Model name cannot be empty")


@dataclass
class BookURL:
    """A publicly accessible URL from the deployed Docusaurus book site that contains content to be processed."""

    url: str
    status: str  # pending, processing, completed, failed
    title: str = ""
    last_crawled_at: Optional[datetime] = None
    crawl_attempts: int = 0
    error_message: str = ""

    def __post_init__(self):
        """Validate the BookURL after initialization."""
        if not self.url:
            raise ValueError("URL cannot be empty")
        valid_statuses = ["pending", "processing", "completed", "failed"]
        if self.status not in valid_statuses:
            raise ValueError(f"Status must be one of {valid_statuses}")


@dataclass
class ProcessingMetadata:
    """Information about each text chunk including source URL, position in document, and processing timestamps."""

    text_chunk_id: str
    source_url: str
    document_title: str = ""
    section_path: str = ""
    processing_started_at: Optional[datetime] = None
    processing_completed_at: Optional[datetime] = None
    embedding_generated: bool = False
    additional_metadata: Dict[str, str] = None

    def __post_init__(self):
        """Validate the ProcessingMetadata after initialization."""
        if not self.text_chunk_id:
            raise ValueError("Text chunk ID cannot be empty")
        if not self.source_url:
            raise ValueError("Source URL cannot be empty")
        if self.additional_metadata is None:
            self.additional_metadata = {}