// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar configuration for the book
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: Robotic Nervous System (ROS 2)',
      link: {type: 'doc', id: 'module-1-robotic-nervous-system/index'},
      items: [
        'module-1-robotic-nervous-system/chapter-1-ros2-basics',
        'module-1-robotic-nervous-system/chapter-2-python-ros2',
        'module-1-robotic-nervous-system/chapter-3-urdf-modeling',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      link: {type: 'doc', id: 'module-2-digital-twin/index'},
      items: [
        'module-2-digital-twin/chapter-1-gazebo-physics',
        'module-2-digital-twin/chapter-2-environment-modeling',
        'module-2-digital-twin/chapter-3-sensor-simulation',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: AI Robot Brain (NVIDIA Isaac)',
      link: {type: 'doc', id: 'module-3-ai-robot-brain/index'},
      items: [
        {
          type: 'category',
          label: 'Chapter 1: NVIDIA Isaac Sim Photorealistic Simulation',
          link: {type: 'doc', id: 'module-3-ai-robot-brain/chapter-1-nvidia-isaac-sim-photorealistic-simulation'},
          items: [
            'module-3-ai-robot-brain/chapter-1-exercises',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2: Isaac ROS for VSLAM and Navigation',
          link: {type: 'doc', id: 'module-3-ai-robot-brain/chapter-2-isaac-ros-vslam-navigation'},
          items: [
            'module-3-ai-robot-brain/chapter-2-exercises',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3: NAV Path Planning for Humanoid Robots',
          link: {type: 'doc', id: 'module-3-ai-robot-brain/chapter-3-nav-path-planning-humanoid-robots'},
          items: [
            'module-3-ai-robot-brain/chapter-3-exercises',
          ],
        },
        'module-3-ai-robot-brain/solutions-guide',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      link: {type: 'doc', id: 'module-4-vla/index'},
      items: [
        {
          type: 'category',
          label: 'Chapter 1: Voice-to-Action (Whisper Integration)',
          link: {type: 'doc', id: 'module-4-vla/chapter-1-voice-to-action-whisper'},
          items: [],
        },
        {
          type: 'category',
          label: 'Chapter 2: Cognitive Planning (LLM → ROS 2)',
          link: {type: 'doc', id: 'module-4-vla/chapter-2-cognitive-planning-llm'},
          items: [],
        },
        {
          type: 'category',
          label: 'Chapter 3: Capstone - Autonomous Humanoid',
          link: {type: 'doc', id: 'module-4-vla/chapter-3-capstone-autonomous-humanoid'},
          items: [],
        },
      ],
    },
  ],
};

export default sidebars;
